### ISSUE TITLE
2주차 과제 TODO 리스트

### ISSUE THREAD

**Issue by JunHoPark93** [JunHoPark93/clean-code#1]
- [ ] 기능 요구사항을 만족하였는가?
 - [ ] 프로그래밍 요구사항을 만족하였는가?
 - [ ] 과제 진행 요구사항을 만족하였는가?
